name: Publish

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm run build
            - run: npm run test
            - name: Setup .npmrc file to publish to npm
              run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: npx lerna publish from-package --yes
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
